### ISSUE TITLE
FAQ to ward off likely flames

### ISSUE THREAD

**Issue by scoskey** [pkra/laml#20]
We spent a good deal of time thinking before arriving at our approach.

**Comment by scoskey** [comment]
Started to write in fcde834, but I wouldn't say this is closed yet.

**Comment by scoskey** [comment]
Continued in ea1d3e2.

**Comment by scoskey** [comment]
Ok, good enough for a start.

**Comment by pkra** [comment]
We might want to test out converting to TeX using pandoc.
